#
#   Copyright 2020 Thomas Bonk <thomas@meandmymac.de>
#
#   Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.
#

name: repti
description: Repti is an application for managing data of the reptiles that you are keeping.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.0.1+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.0
  flutter_platform_widgets: ^0.70.2
  dart_inject: ^1.0.0
  event_bus: ^1.1.1
  # ORM
  floor: ^0.17.0
  sqflite: ^1.3.0
  uuid: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  floor_generator: ^0.17.0
  build_runner: ^1.10.3

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
